from operator import attrgetter
from itemset_mining.two_phase_huim import TwoPhase


transactions = [
    [("Coke 12oz", 6), ("Chips", 2), ("Dip", 1)],
    [("Coke 12oz", 1)],
    [("Coke 12oz", 2), ("Chips", 1), ("Filet Mignon 1lb", 1)],
    [("Chips", 1)],
    [("Chips", 2)],
    [("Coke 12oz", 6), ("Chips", 1)]
]

print(transactions)

# lợi nhuận trung bình của mỗi sản phẩm
external_utilities = {
    "Coke 12oz": 5,
    "Chips": 23,
    "Dip": 17,
    "Filet Mignon 1lb": 2
}

# Minimum dollar value generated by an itemset we care about across all transactions
minutil = 20.00

hui = TwoPhase(transactions, external_utilities, minutil)
result = hui.get_hui()
# print(sorted(result, key=attrgetter('itemset_utility'), reverse=True))


...  # doctest: +NORMALIZE_WHITESPACE
# [HUIRecord(items=('Chips', 'Coke 12oz'), itemset_utility=30.02),
#  HUIRecord(items=('Chips', 'Coke 12oz', 'Filet Mignon 1lb'), itemset_utility=28.56),
#  HUIRecord(items=('Chips', 'Filet Mignon 1lb'), itemset_utility=25.979999999999997),
#  HUIRecord(items=('Coke 12oz', 'Filet Mignon 1lb'), itemset_utility=25.57),
#  HUIRecord(items=('Filet Mignon 1lb',), itemset_utility=22.99),
#  HUIRecord(items=('Chips',), itemset_utility=20.93)]
